### PR TITLE
Update harbour-webcat-es.ts

### PR DESCRIPTION
**Pull request by Caballlero**
=  )

### CODE REVIEW

**Comment by Caballlero** [comment]
Hi llelectronics

I want to know why not merged my pull request before the release? this included CookieManager sentences translated .

**Comment by llelectronics** [comment]
Oh sorry. I thought I merged it already :P

**Comment by Caballlero** [comment]
Thank you

**Comment by carmenfdezb** [comment]
I've done translation to Spanish language via Transifex too. Some texts in Caballlero translations are in Latin Spanish, not in Spanish from Spain

**Comment by Caballlero** [comment]
What is the problem carmen F.B ??? if it is the same language Spanish, the difference is that you do not optimize the words about a GUI and other things that are missing too.

**Comment by carmenfdezb** [comment]
You know that Spanish and Latin Spanish are not the same. For example, 'Jalar' doesn't exist in Spanish language. I'm tranlating this project, why you change my translations?

**Comment by Caballlero** [comment]
I started to trasnlate this app because look like abandoned on spanish  translation, so i am ok if 
llelectronics prefered your *es.ts file. But remember this "Webcat Project" not "AviaTicket project" so take care my default browser. 
Then on the word "jalar" you are right ,this a error resolved to my internal *es.ts file and other think too. HALAR.

**Comment by Caballlero** [comment]
You too modified-es.ts Talefish project when i am the translator. Why you change my translations?

**Comment by carmenfdezb** [comment]
It's not abandoned, I didn't know Webcat was updated until I open Warehouse.
I think 'Jalar' is 'Deslizar' in Spanish language we don't use that word (Jalar)

**Comment by carmenfdezb** [comment]
I didn't modify your translation in Talefish, I was accepted like translator in Transifex and I completed the translation there

**Comment by carmenfdezb** [comment]
Sincerely, I don't want more polemics with you. If you want to translate this project for me it is perfect, but I did the same work in Transifex.

**Comment by Caballlero** [comment]
@carmenfdezb  In this case can you tell  me what words you are not right with me on my spanish(translation), because you say many time that my spanish it is not the same with you spanish.

**Comment by Caballlero** [comment]
Also i am ok with you on not to use the word jalar or halar to say slide , note that in this case is not my problem because the developer wrote" Pull down" the the correct translate is "jalar or halar", if the developer would wrote "Slide down" i would translate to "deslizar hacia abajo"  i like deslizar instead halar, because halar it not usefull.

**Comment by Caballlero** [comment]
I think that the problem is because llelectronics not refreshed the file to transfifex. However, I want you and me to work together without any complaints. VALE !

**Comment by carmenfdezb** [comment]
For me it's perfect, we need translators in Sailfish. But please, use words from Spain to translate text in Spanish (Spain).

**Comment by llelectronics** [comment]
Yes I did not update the transifex locale for spanish. My mistake. Usually transifex picks up the translations from git. This might be broken for this case. 
In general its way easier if you @Caballlero would add yourself to the list of translators over in transifex. 
Then you two can discuss things over there when it comes to translations.

**Comment by Caballlero** [comment]
You are right @llelectronics. I will ...

**Comment by carmenfdezb** [comment]
Hi @llelectronics !
I've translated last version (2.9.1) to Spanish language, but again, @Caballlero did the same via Github. The text that he's translated is different than mine, so I would like you fix credits in Spanish translations because I'm not the author.
On the other hands, I should have been warned that you will use translations via Github.
Thanks in advance!

**Comment by llelectronics** [comment]
Ok for the future I need to make a decision here now which translation to use. 
I will only accept translations now via transifex just like all other translations (except the german one as I do this myself) 

@Caballlero if you want to have further influence on the spanish translations please use transifex. 
@carmenfdezb Conclusion from my decision now is to import your translation so it will be featured in future releases.

**Pull request merged**
