### PR TITLE
Improved night mode + swipe on toolbar

### PR DESCRIPTION
**Pull request by Dharmendra63**
https://openrepos.net/content/dharmendra63/webcat-night-mode-swipe-toolbar-switch-tab

### CODE REVIEW

**Comment by llelectronics** [comment]
In general I like to implement a few of those features. But those need some editing. 
The reader mode is something I don't want to throw out. The addition of the dark and normal mode however would be quite interesting. 

Swipe on toolbar is a nice addition.  And yep with some graphical adjustment that can work pretty nice. 
However the quick changing of tabs is already implemented so why adding it as swipe feature on the toolbar aswell? 

I could make that configurable. Though it needs some changes for the setting variable itself. This 0 and 1 by reading the code confused me. Maybe that can be changed to a string instead.

I will take a look at that later this month when I am back from vacation.

**Comment by Dharmendra63** [comment]
Please make reader mode separate from dark-normal mode
I liked the swipe way of changing tabs in chrome android so I thought I'll put it here. What do you mean by already available "quick changing of tabs" in webcat?

**Comment by llelectronics** [comment]
By quick changing I mean you can press and hold the tab/goto button bottom left if you have more than 1 tab open and it will show the current tab and allows you to change to the other one by moving the finger up until the correct tab is choosen and then let go.

**Comment by llelectronics** [comment]
Added this commit which implements nightmode: https://github.com/llelectronics/webcat/commit/370e209a1f36df234632d42590a17aeb707db120

**Comment by llelectronics** [comment]
Also worked on a new UI for tabbar and bookmarks that allows faster switching between tabs. See this teaser video: https://youtu.be/dTvZAVv6uEQ
Double Tap on the tab/goto button in the toolbar bottom left switches to the previous tab also :)

**Pull request closed without merging**
